spring.datasource.url=${NOTIFICATION_DB_URL}
spring.datasource.username=${NOTIFICATION_DB_USERNAME}
spring.datasource.password=${NOTIFICATION_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
