spring.datasource.url=${NOTIFICATION_DB_URL:jdbc:mysql://localhost:3310/blog_notifications}
spring.datasource.username=${NOTIFICATION_DB_USERNAME:notification_user}
spring.datasource.password=${NOTIFICATION_DB_PASSWORD:notification_password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
