spring.datasource.url=${IDENTITY_DB_URL}
spring.datasource.username=${IDENTITY_DB_USERNAME}
spring.datasource.password=${IDENTITY_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
