spring.datasource.url=${IDENTITY_DB_URL:jdbc:mysql://localhost:3307/blog_identity}
spring.datasource.username=${IDENTITY_DB_USERNAME:identity_user}
spring.datasource.password=${IDENTITY_DB_PASSWORD:identity_password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
