apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
data:
  SPRING_PROFILES_ACTIVE: prod
  IDENTITY_MYSQL_DATABASE: blog_identity
  IDENTITY_DB_USERNAME: identity_user
  POST_MYSQL_DATABASE: blog_posts
  POST_DB_USERNAME: post_user
  CONTENT_MYSQL_DATABASE: blog_content
  CONTENT_DB_USERNAME: content_user
  NOTIFICATION_MYSQL_DATABASE: blog_notifications
  NOTIFICATION_DB_USERNAME: notification_user
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_NOTIFICATION_GROUP_ID: notification-service-v1
  POST_PUBLISHED_TOPIC: blog.posts.published.v1
  POST_PUBLISHED_DLT_TOPIC: blog.posts.published.v1.DLT
  JWT_EXPIRATION_MS: "18000000"
  CONTENT_HTTP_CONNECT_TIMEOUT: 2s
  CONTENT_HTTP_READ_TIMEOUT: 5s
  CORS_ALLOWED_ORIGINS: http://localhost:30080,http://127.0.0.1:30080,http://192.168.49.2:30080
  AUTH_COOKIE_NAME: BLOG_ACCESS_TOKEN
  AUTH_COOKIE_SECURE: "false"
  AUTH_COOKIE_SAME_SITE: Lax
