apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog-platform
resources:
  - namespace.yaml
  - configmap.yaml
  - mysql.yaml
  - kafka.yaml
  - applications.yaml
  - frontend.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: blog-platform
