#DB Configurations
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/blog_app_apis}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
