spring.datasource.url=${POST_DB_URL:jdbc:mysql://localhost:3308/blog_posts}
spring.datasource.username=${POST_DB_USERNAME:post_user}
spring.datasource.password=${POST_DB_PASSWORD:post_password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
