spring.datasource.url=${CONTENT_DB_URL:jdbc:mysql://localhost:3309/blog_content}
spring.datasource.username=${CONTENT_DB_USERNAME:content_user}
spring.datasource.password=${CONTENT_DB_PASSWORD:content_password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
