spring.datasource.url=${CONTENT_DB_URL}
spring.datasource.username=${CONTENT_DB_USERNAME}
spring.datasource.password=${CONTENT_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
